<a href="https://colab.research.google.com/github/Ashish05032007/Ashish05032007/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing Numpy**

In [ ]:
import numpy as np

**Creating** Array from List

In [ ]:
arr_1d=np.array([1,2,3,4,5])
print("1D array: ",arr_1d)
arr_2d=np.array([[1,2,3],[4,5,6]])
print("2D array: ",arr_2d)#we only add single array as argument

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


**List vs numpy array**

In [ ]:
py_list=[1,2,3]
print("Python List Multiplication", py_list*2)#List multiplication duplicates the entire list. It's a form of repetition, not element-wise arithmetic

np_array=np.array([1,2,3])
print("Python Array Multiplication", np_array*2)#

import time

start=time.time()
np_array=np.arange(1000000)*2#np.arange is a NumPy function that
# creates a NumPy array with evenly spaced values within a specified interval. It's similar to Python's built-in range() function but returns an array instead of a list.
print("\n Numpy operation time:", time.time()-start)


Python List Multiplication [1, 2, 3, 1, 2, 3]
Python Array Multiplication [2 4 6]

 Numpy operation time: 0.011434793472290039


**Creatin array from Scratch**

In [ ]:
zero=np.zeros((3,4))#(row,column isthe argument)
print("\n zero array:\n", zero)

ones=np.ones((2,3))
print("\n ones array\n", ones)\

#constant array

full=np.full((2,2), 7)# argument is ((dimension),value of constant)
print("\n full array\n", full)

random=np.random.random((2,3))
print("\nRandom array\n", random)# random values lies between 0 and 1

sequence=np.arange(0,10,2)# in Python range's outer boundary is non-exclusive.
print("\n sequence array\n", sequence)



 zero array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 ones array
 [[1. 1. 1.]
 [1. 1. 1.]]

 full array
 [[7 7]
 [7 7]]

Random array
 [[0.8551954  0.92461622 0.30522771]
 [0.24487983 0.31701037 0.17878269]]

 sequence array
 [0 2 4 6 8]


***Vector, Matrix and Tensor***

In [ ]:
vector=np.array([1,2,3])
print("vector:",vector)

matrix=np.array([[1,2,3],
                [4,5,6]])
print("Matrix", matrix)

tensor=np.array([
                 [[1,2],[2,3]],
                 [[4,5],[6,7]]
                 ])

print("tensor:",tensor)

vector: [1 2 3]
Matrix [[1 2 3]
 [4 5 6]]
tensor: [[[1 2]
  [2 3]]

 [[4 5]
  [6 7]]]


**Array Properties**

In [ ]:
arr=np.array([[1,2,3],
              [4,5,6]])
print("Shape",arr.shape)
print("dimension",arr.ndim)
print("size",arr.size)
print("datatype", arr.dtype)

arr=np.array([[1,2,3],
              [4,5,True]])# different datatype can be put in array but recommend to use single data-type
print("Shape",arr.shape)
print("dimension",arr.ndim)
print("size",arr.size)
print("datatype", arr.dtype)


Shape (2, 3)
dimension 2
size 6
datatype int64


**Array Reshaping**

In [ ]:
arr=np.arange(12)
print("Original array", arr)

reshaped=arr.reshape((3,4))
print("Reshaped array", reshaped)

flattened=reshaped.flatten()
print("flattened array", flattened)

raveled=reshaped.ravel()
print("ravelled array", raveled)# ravel returns view instead of copy

#Transpose of a matrix
transpose=reshaped.T
print("Transposed array", transpose)

Original array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11]
ravelled array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


**NUMPY ARRY OPERATIONS**

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print("Slicing",arr[2:7])
print("With step", arr[1:8:2])
print("Negative indexing", arr[-3])

arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

print("specific element", arr_2d[2,2])
print("entire row", arr_2d[1])
print("entire column", arr_2d[:,1])

Slicing [3 4 5 6 7]
With step [2 4 6 8]
Negative indexing 7
specific element 9
entire row [4 5 6]
entire column [2 5 8]


**SORTING**

In [ ]:
unsorted=np.array([3,1,4,1,5,9,2,6])
print("Sorted array", np.sort(unsorted))

array_2d_unsorted=np.array([[3,1],[1,2],[2,3]])
#print("Sorted 2d array by column", np.sort(array_2d_unsorted, axis=0))#sort top to bottom
print("Sorted 2d array by column", np.sort(array_2d_unsorted, axis=1))#sort left to right

Sorted array [1 1 2 3 4 5 6 9]
Sorted 2d array by column [[1 3]
 [1 2]
 [2 3]]


**FILTERING**

In [ ]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers=numbers[numbers%2==0]
print("Even:", even_numbers)

Even: [ 2  4  6  8 10]


**Filter with mask**

In [ ]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
mask=numbers>5

print("number greater than 5:", numbers[mask])

number greater than 5 [ 6  7  8  9 10]


**FANCY INDEXING VS NP.WHERE()**

In [ ]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
indices=[0,2,4]
print(numbers[indices])

where_result=np.where(numbers>5)
print(where_result)
print("NP where",numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


**CONDITION ARRAY**

In [ ]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
condition_array=np.where(numbers>5,numbers, numbers)
print(condition_array)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
#condition_array=np.where(numbers>5,numbers84, numbers)
#condition_array=np.where(numbers>5,numbers, numbers)
condition_array=np.where(numbers>5,"true", "false")
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


**ADDING AND REMOVING DATA**

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
merged_array_wrong=arr1+arr2
print(merged_array_wrong)#this is wrong method to concatenate array

merged_array_right=np.concatenate((arr1,arr2))# array1 and array2 are passed to argument of concatenate as tuple
print(merged_array_right)






[5 7 9]
[1 2 3 4 5 6]


**ARRAY COMPATABILITY**

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9,10])

print("Compatibilty Shapes: ", a.shape==b.shape)#outputs true
print("Compatibilty Shapes: ", a.shape==c.shape)#outputs false



Compatibilty Shapes:  True


**ADDING ROWS AND COLUMN**

In [ ]:
original = np.array([[1, 2], [2, 3], [3, 4]])  # Shape: (3, 2)
print("Original:\n", original, "\n")


new_row = np.array([[5, 6]])                  # Shape: (1, 2)
with_the_row = np.vstack((original, new_row)) # Works fine, shape becomes (4, 2)
print("After adding new row:\n", with_the_row, "\n")


#new_col = np.array([[7], [9]])                # Shape: (2, 1)
#with_the_col = np.hstack((original, new_col)) # ❌ This will raise a ValueError

new_col = np.array([[7], [8], [9]])  # Now shape is (3, 1)
with_the_col = np.hstack((original, new_col))
print("After adding new column:\n", with_the_col)





Original:
 [[1 2]
 [2 3]
 [3 4]] 

After adding new row:
 [[1 2]
 [2 3]
 [3 4]
 [5 6]] 

After adding new column:
 [[1 2 7]
 [2 3 8]
 [3 4 9]]


**DELETING ARRAY**

In [ ]:
arr=np.array([1,2,3])
deleted=np.delete(arr,2)
print(deleted)#return array after deletion

[1 2]
